name: codar_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope
  - asn1crypto
  - backcall
  - blas
  - bleach
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - chardet
  - cryptography
  - curl
  - cycler
  - decorator
  - entrypoints
  - freetype
  - geos
  - html5lib
  - icu
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - kiwisolver
  - krb5
  - libiconv
  - libpng
  - libprotobuf
  - libsodium
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - matplotlib
  - mistune=
  - mysql-connector-python
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - olefile
  - openblas
  - openssl
  - owslib
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - proj4
  - prompt_toolkit
  - protobuf
  - ptyprocess
  - pycparser
  - pyepsg
  - pygments
  - pyopenssl
  - pyproj
  - pyqt
  - pyshp
  - pysocks
  - pyzmq
  - qt
  - qtconsole
  - requests
  - scipy
  - send2trash
  - shapely
  - simplegeneric
  - sip
  - sqlalchemy
  - terminado
  - testpat
  - traitlets
  - urllib3
  - wcwidth
  - webencodings
  - widgetsnbextension
  - zeromq
  - bokeh
  - bzip2
  - click
  - cloudpickle
  - cytoolz
  - dask
  - dask-core
  - distributed
  - hdf4
  - hdf5
  - heapdict
  - intel-openmp
  - jinja2
  - jpeg
  - libcurl
  - libcxx
  - libcxxabi
  - libedit
  - libffi
  - libgfortran
  - libnetcdf
  - libssh2
  - locket
  - markupsafe
  - mkl
  - mkl_fft
  - mkl_random
  - msgpack-python
  - ncurses
  - netcdf4
  - packaging
  - pandas
  - partd
  - pip
  - psutil
  - pyparsing
  - python
  - python-dateutil
  - pytz
  - pyyaml
  - readline
  - setuptools
  - six
  - sortedcontainers
  - sqlite
  - tblib
  - tk
  - toolz
  - tornado
  - wheel
  - xarray
  - xz
  - yaml
  - zict
  - zlib
  - pip:
    - gsw
    - oceans
    - seawater

