name: codar_processing
channels:
  - conda-forge
  - defaults
dependencies:
  - xarray
  - netcdf4
  - dask
  - sqlalchemy
  - mysql-connector-python   
  - scipy
  - geopandas
  - cyordereddic
  - cartopy
  - oceans
  - gsw
  - seawater
  - jupyter
  - numba